In [37]:
import pandas as pd  
import numpy as np  
import pandas as pd
import seaborn as sns
import statsmodels.formula.api as smf
from sklearn.linear_model import LinearRegression
from sklearn import metrics
#from sklearn.cross_validation import train_test_split
import numpy as np
import matplotlib.pyplot as plt  
%matplotlib inline

In [38]:
data=pd.read_excel('Data.xlsx')

In [39]:
data.head()

Leads  Wins
0   2399   747
1   4474   700
2   3117   691
3   5150   889
4   3720  1369

In [40]:
data.describe()


Leads         Wins
count    106.000000   106.000000
mean    4131.518868  1304.575472
std     1389.188007   684.356256
min       56.000000   648.000000
25%     3335.000000   882.500000
50%     3956.500000  1039.500000
75%     4901.500000  1574.500000
max    10013.000000  3784.000000

In [41]:
X = data.iloc[:, :-1].values  
y = data.iloc[:, :2].values  

In [42]:
print(X)
print(y)

[[ 2399]
 [ 4474]
 [ 3117]
 [ 5150]
 [ 3720]
 [ 3913]
 [ 4053]
 [ 3951]
 [ 4951]
 [ 6928]
 [ 4331]
 [ 5186]
 [ 5556]
 [ 3878]
 [ 3305]
 [ 3539]
 [ 5402]
 [ 3971]
 [ 4774]
 [ 8224]
 [ 4996]
 [ 3894]
 [ 5081]
 [ 4649]
 [ 5021]
 [ 4917]
 [ 2650]
 [ 3519]
 [ 4765]
 [ 5519]
 [ 4022]
 [ 5131]
 [ 6092]
 [ 3896]
 [ 3551]
 [ 3811]
 [ 5529]
 [ 4996]
 [ 4753]
 [ 3920]
 [ 4039]
 [ 4444]
 [ 5192]
 [ 3757]
 [ 4728]
 [ 4294]
 [ 3280]
 [ 4532]
 [ 5245]
 [10013]
 [ 3828]
 [ 1719]
 [   56]
 [ 2395]
 [ 3451]
 [ 3197]
 [ 3516]
 [ 4301]
 [ 4770]
 [ 3601]
 [ 6929]
 [ 5047]
 [ 5922]
 [ 4072]
 [ 4855]
 [ 4123]
 [ 2823]
 [ 2362]
 [ 4111]
 [ 3826]
 [ 2971]
 [ 3962]
 [ 3609]
 [ 3065]
 [ 3600]
 [ 5244]
 [ 4309]
 [ 6782]
 [ 5224]
 [ 2410]
 [ 3640]
 [ 3813]
 [ 3819]
 [ 3523]
 [ 4743]
 [ 3350]
 [ 2928]
 [ 3830]
 [ 3289]
 [ 4630]
 [ 4612]
 [ 3605]
 [ 2739]
 [ 2956]
 [ 3330]
 [ 3160]
 [ 3012]
 [ 3013]
 [ 3141]
 [ 2460]
 [ 3181]
 [ 7150]
 [ 5071]
 [ 4204]
 [ 1304]
 [  300]]
[[ 2399   747]
 [ 4474   700]
 [ 3117   691]


In [43]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [64]:
from sklearn.linear_model import LinearRegression  
regressor = LinearRegression()  
regressor.fit(X_train, y_train)  


print(y_train)

[[ 2650   648]
 [ 3605  2462]
 [ 3896   894]
 [ 5150   889]
 [ 2823  1648]
 [ 5245  1046]
 [ 4022  1573]
 [ 4053   805]
 [ 5224  3784]
 [ 2956   954]
 [ 3640   911]
 [ 2739  1963]
 [ 3819  1085]
 [ 3601  1011]
 [ 3519   790]
 [ 4774   757]
 [ 5047  2082]
 [ 1719  2822]
 [ 4072  1102]
 [ 3962   962]
 [ 3757  1737]
 [ 4474   700]
 [ 2410  1575]
 [ 5192   998]
 [ 4444   866]
 [ 3720  1369]
 [ 3539   764]
 [ 3971  1247]
 [ 4039   791]
 [ 4753  3124]
 [ 3913   718]
 [ 2395  1694]
 [ 3013   851]
 [ 3516   820]
 [ 2399   747]
 [ 3551  1716]
 [ 4765   802]
 [ 3197   837]
 [ 3828  1885]
 [ 5186  1068]
 [ 5922   980]
 [ 3811   823]
 [ 4649   935]
 [ 5131   828]
 [ 3160   966]
 [ 4301  1946]
 [ 2928  1281]
 [ 4612  1365]
 [ 6092   837]
 [ 4630  1038]
 [ 3305   668]
 [ 3600  2298]
 [ 8224   875]
 [ 5519  1094]
 [10013  1235]
 [ 4204  2008]
 [ 1304  1996]
 [ 3826  1255]
 [ 4996  1024]
 [ 3181  2208]
 [ 3609  1042]
 [ 6782  1214]
 [ 4917  3555]
 [ 4996  1100]
 [ 3813   963]
 [ 3280   830]
 [ 3012  2

In [65]:
print(regressor.intercept_)  

[2.72848411e-12 1.53467050e+03]


In [66]:
print(regressor.coef_)

[[ 1.        ]
 [-0.03568681]]


In [67]:
y_pred = regressor.predict(X_test)  
print(X_test)

[[2460]
 [4331]
 [5244]
 [3117]
 [5021]
 [3141]
 [ 300]
 [3951]
 [5402]
 [3350]
 [4111]
 [5081]
 [4294]
 [6929]
 [4309]
 [  56]
 [3878]
 [3065]
 [4743]
 [3451]
 [7150]
 [4951]]


In [68]:
print(y_pred)

[[2460.         1446.88095465]
 [4331.         1380.11093691]
 [5244.         1347.52888121]
 [3117.         1423.4347218 ]
 [5021.         1355.4870394 ]
 [3141.         1422.57823841]
 [ 300.         1523.96445991]
 [3951.         1393.67192394]
 [5402.         1341.89036555]
 [3350.         1415.11969554]
 [4111.         1387.96203466]
 [5081.         1353.34583092]
 [4294.         1381.4313488 ]
 [6929.         1287.39660975]
 [4309.         1380.89604668]
 [  56.         1532.67204106]
 [3878.         1396.27706093]
 [3065.         1425.29043582]
 [4743.         1365.40797202]
 [3451.         1411.51532794]
 [7150.         1279.50982519]
 [4951.         1357.98511595]]


In [57]:
df = pd.DataFrame({'Actual': y_test[2], 'Predicted': y_pred[2]})  
df 

<bound method DataFrame.all of    Actual    Predicted
0    5244  5244.000000
1     975  1347.528881>

In [69]:
from sklearn import metrics  
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test[0], y_pred[0]))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test[0], y_pred[0]))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test[0], y_pred[0])))  

Mean Absolute Error: 281.440477326278
Mean Squared Error: 158417.48455528566
Root Mean Squared Error: 398.01694003557895


In [59]:
accuracy = regressor.score(X_test,y_test)

In [62]:
print(accuracy*100)

92.23964753309612
